# Site
name: "L.M Landscapes"
title: "L.M Landscapes"
description: "L.M Landscapes & Property Maintenance"
logo: 'assets/images/logolm.png'
logofooter: 'assets/images/logolmfooter.png'
favicon: 'assets/images/favicon.ico'
baseurl: /home
google_analytics: 'UA-46278016-1'
disqus: 'demowebsite'
homepageurl: "https://lmlandscapes.github.io/home/"
mailchimp-list: 'https://wowthemes.us11.list-manage.com/subscribe/post?u=8aeb20a530e124561927d3bd8&amp;id=8c3d2d214b'
include: ["_pages"]
permalink: /:title/
fburl: "https://www.facebook.com/lloydsLandscape/"
instaurl: "https://www.instagram.com/l.m_landscapes/"
developer: "Gosu"

# Authors
authors:
  lloyd:
    name: Lloyd
    display_name: Lloyd
    avatar: 'assets/images/lloyd.png'
    # gravatar: e56154546cf4be74e393c62d1ae9f9d4
    email: lloyd-1994@hotmail.com
    web: https://www.facebook.com/miles.lloyd.3/
    description: "I am Lloyd, founder of L.M Landscapes."
  sal:
    name: Sal
    display_name: Sal
    gravatar: e56154546cf4be74e393c62d1ae9f9d4
    email: wowthemesnet@gmail.com
    web: https://www.wowthemes.net
    twitter: https://twitter.com/wowthemesnet
    description: "Author of Mediumish, a Bootstrap Medium styled template available for WordPress, HTML, Ghost and Jekyll. You are currently previewing Jekyll template demo."
  john:
    name: John
    display_name: John    
    avatar: 'assets/images/avatar.png'
    gravatar: b1cc14991db7a456fcd761680bbc8f81
    email: wowthemesnet@gmail.com
    web: https://www.wowthemes.net
    twitter: https://twitter.com/wowthemesnet
    description: "This is the author box. Write a short description of the author here. You are currently previewing Mediumish demo, a Jekyll template compatible with Github pages."

# Plugins
plugins:
  - jekyll-paginate
  - jekyll-sitemap
  - jekyll-feed
  - jekyll-seo-tag
  - jekyll-archives
    
# Archives
jekyll-archives:
  enabled:
    - categories
  layout: archive
  permalinks:
    category: '/category/:name/'
    
# Pagination 
paginate: 6
paginate_path: /page:num/
    
# Other
markdown: kramdown

kramdown:
  input: GFM
  syntax_highlighter: rouge
  syntax_highlighter_opts:
    block:
      line_numbers: true

# Adsense (change to "enabled" to activate, also your client id and ad slot. Create a new ad unit from your Adsense account to get the slot.)
adsense: "disabled"
adsense-data-ad-client: "ca-pub-3412143450191416"
adsense-data-ad-slot: "1363087678"

# Lazy Images ("enabled" or "disabled")
lazyimages: "disabled"

exclude: [changelog.md, LICENSE.txt, README.md, Gemfile, Gemfile.lock]

- selector: slider1
  bullets: false
  captions: true
  images:
    - src: /img/1.jpg
      alt: Minimum required attributes
    - data-src: /img/2.jpg
      alt: Use data-src for on-demand loading
    - data-src: /img/3.jpg
      data-src-2x: /img/3@2x.jpg
      alt: Use data-src-2x for HiDPI devices
    - src: /img/4.jpg
      alt: Links work too
      href: https://github.com/jekylltools/jekyll-ideal-image-slider-include
  settings:
    height: 400
    initialHeight:
    maxHeight:
    interval:
    transitionDuration:
    effect:
    disableNav:
    keyboardNav:
    previousNavSelector:
    nextNavSelector:

- selector: slider2
  bullets: true
  captions: true
  images:
    - src: /img/1.jpg
      title: Balloons!
      alt: This slider has caption titles
    - data-src: /img/2.jpg
      title: This slider uses the fade effect
      alt: Instead of the default slide effect
    - data-src: /img/3.jpg
      data-src-2x: /img/3@2x.jpg
    - src: /img/4.jpg
      title: Last image had no caption!
      alt: Also, this image has no link
  settings:
    height: "'auto'"
    effect: "'fade'"

- selector: slider3
  images:
    - src: /img/1.jpg
      alt: image one
    - src: /img/2.jpg
      alt: image two
    - src: /img/3.jpg
      alt: image three
    - src: /img/4.jpg
      alt: image four
  settings:
    height: "'auto'"
    disableNav: true
